server:
  Application: ""
  AppVersion: 1.0.0
  Port: 6555

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: trace

mongodb:
 hosts: localhost:27017
 db_name: rest_api_development
 username: guest
 password: guest
 timeout: 10
 dial_timeout: 10
 pool_size: 10
 auth_source:
 replica_set:
 uri: